# 8 items in each
shop-items:
  mining:
    # material, displayname, buy, sell
    - diamond;test;100;100
    - diamond;test;100;100
    - diamond;test;100;100
    - diamond;test;100;100
    - diamond;test;100;100
    - diamond;test;100;100
    - diamond;test;100;100
    - diamond;test;100;100
  alchemy:
    - gold;gold;100;100
    - gold;gold;100;100
    - gold;gold;100;100
    - gold;gold;100;100
    - gold;gold;100;100
    - gold;gold;100;100
    - gold;gold;100;100
    - gold;gold;100;100
  blacksmith:
  mercenary:
  farming: